### ISSUE TITLE
Any plans to support RAML 1.0?

### ISSUE THREAD

**Issue by sichvoge** [tacoss/raml-mockup#13]
Hi there,

stumbled upon your project and wonder whats the status is and if there are any plans to support RAML 1.0?

Thanks,
Christian

**Comment by pateketrueke** [comment]
Actually I didn't get updated on that topic, but let me invest some time on it.

I really love RAML and, we're working on [json-schema-faker](http://json-schema-faker.js.org/) which actually powers up the whole thing!

I'll comment on this on few days, thanks for your feedback!

**Comment by pateketrueke** [comment]
I'm back, `raml-mockup@0.2.0` now supports both RAML 0.8 and 1.0 :beers:
