### ISSUE TITLE
Upgrade json-schema-faker version

### ISSUE THREAD

**Issue by karthilxg** [tacoss/raml-mockup#14]
Any plans to upgrade `json-schema-faker` version to the latest ?

Quite a number of releases happened to `json-scheme-faker` in last few months, would be great if we upgrade it to the latest version.

I need the latest version to address the below issue,

https://github.com/json-schema-faker/json-schema-faker/pull/156

**Comment by karthilxg** [comment]
[PR](https://github.com/gextech/raml-mockup/pull/15)

**Comment by pateketrueke** [comment]
So much thanks for your feedback, I've released `0.1.9` atm! :beers:
