### ISSUE TITLE
Missing resource Error

### ISSUE THREAD

**Issue by rac021** [tacoss/raml-mockup#16]
Hi,
I have the following RAML file :

```
#%RAML 1.0
title: New API
version: v1
baseUri: http://192.168.56.1:8000/{version}
types:
  TestType:
    type: object
    properties:
      id: number
      optional?: string
      expanded:
        type: object
        properties:
          count: number
/planes:
  get:
    description: list planes
    responses:
      200:
        body:
          application/json:
            example: |
             [
              {"Airbus" : "A320" },
              {"Boeing" : "777" }
             ]
```

Launching raml-mockup :

```
  $ raml-mockup simple.raml -f http://json-schema.org -p 5000 -w
     Endpoint:
       http://localhost:5000
       Resources:
          /planes

      Watching for changes...

```

calling the resource : **http://localhost:5000/v1/planes**

gives me the following error :

 **{"error":"Missing resource for /planes"}**

Can anyone tell me what's wrong  ??

Thank's.

**Comment by pateketrueke** [comment]
Currently raml-mockup supports json-schema only, taken this into account, how do you specify which type/schema that given resource will use?

**Comment by rac021** [comment]
I have no specified any schema.
Any idea, timewise, as to when support YAML will be available ?

**Comment by pateketrueke** [comment]
I can examine the support for XML-Schemas asap but I can't guarantee fully support for it soon.

Even I can try to convert someway any type/xml-schema in order to achieve real mocks through json-schema-faker...

Thanks for your feedback!

**Comment by rac021** [comment]
One last question : What about YAML ?

Yhank you @pateketrueke

**Comment by pateketrueke** [comment]
I don't understand, since RAML is yaml-like syntax, do you mean `include` tags and such?

**Comment by rac021** [comment]
What I would like is having the following ( simplistic ) file without any schema :

```
#%RAML 1.0
title: New API
version: v1
baseUri: http://192.168.56.1:8000/{version}

/planes:
  get:
    description: list planes
    responses:
      200:
        body:
          application/json:
            example: |
             [
              {"Airbus" : "A320" },
              {"Boeing" : "777" }
             ]
```

Using this command 

```
  $ raml-mockup simple.raml -p 5000 -w
     Endpoint:
       http://localhost:5000
       Resources:
          /planes

      Watching for changes...

```

and when calling the resource : **http://localhost:5000/v1/planes**

this will gives me :

 **[{"Airbus" : "A320" },{"Boeing" : "777" }**

Thank's

**Comment by pateketrueke** [comment]
I got it, accepting resources without any schema is fine if an example is given?

I think that feature would be awesome, let me think what can I do.

Until I fix it try adding `_forceExample=true` to your request.

**Comment by rac021** [comment]
Yeah, an example which accepts resources without any schema would be interesting.

What means the  **_forceExample = true** ?

**Comment by pateketrueke** [comment]
> What means the _forceExample = true ?

I meant that requesting `http://localhost:5000/planes?_forceExample=true` could do the trick, but I just realized that resources without any schema defined are not even registered.

Just right now I fixed that issue allowing resources to be schema-less, the fallback is always responding with the given example.

Released `raml-mockup@0.2.1` atm! :beers:

**Comment by rac021** [comment]
I just tested , it works fine :-)

Thank's

**Comment by pateketrueke** [comment]
Yay!
