### ISSUE TITLE
Nested schemas are not generated

### ISSUE THREAD

**Issue by ghost** [tacoss/raml-mockup#5]
Changing song-schema.json to

```
{
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "artist": {
      "$ref": "artist-schema.json"
    }
  },
  "required": ["title", "artist"]
}
```

produces the following output:

```
curl http://localhost:5000/songs

[{"title":"et ea rerum","artist":{"$ref":"artist-schema.json"}},{"title":"et totam aut quo iusto","artist":{"$ref":"artist-schema.json"}}]
```

Expecting a randomly generated artist object.

**Comment by pateketrueke** [comment]
I will assume that `artist-schema.json` is in the same folder as `song-schema.json` right?

Are both listed within the `schemas` property in your RAML?

**Comment by ghost** [comment]
Correct. I actually simply downloaded and tested this bug on the files under raml-mockup/spec/fixtures/ to ensure it wasn't an issue with my raml/schema files.

**Comment by pateketrueke** [comment]
Fine, then let me check what can I do for solving this asap. Thanks for your feedback!

**Comment by pateketrueke** [comment]
I've updated all the dependencies and ran `raml-mockup spec/fixtures/api.raml --fakeroot http://json-schema.org --directory spec/fixtures/schemas --formats $PWD/spec/formats/index.js`

Also I've edited the `song-schema.json` as you expect and the results are OK this time.

Please update to `0.1.6` and let me know if the issue persists.

:beers:

**Comment by ghost** [comment]
Nailed it! Fastest fix ever. Thanks!
