### ISSUE TITLE
Error resolving nested schemas

### ISSUE THREAD

**Issue by menehune23** [tacoss/raml-mockup#6]
I'm having issues getting responses that require nested schemas. Just to be sure, I tested it with the "fixtures" example (no file changes), running from both inside and outside the "fixtures" directory:

`raml-mockup fixtures/api.raml -d fixtures/schemas -f http://json-schema.org -p 5000 -r $PWD/formats/index.js -w`

Output:

```
Watching for changes...
Endpoint:
  http://localhost:5000
Resources:
  /songs
    GET      -> 200
  /songs/:id
    GET      -> 200
  /artists/:name
    GET      -> 200, 404
```

In a separate command window, running:

`curl http://localhost:5000/songs`

produces the response:

`{"error":"Reference not found: http://json-schema.org/song-schema.json#"}`
- Note that this is _song-schema.json_, the nested schema, not _song-schema**s**.json_, the outer schema

Meanwhile, the following is appended to the raml-mockup output:

```
/songs
    GET      -> 500
```

This almost exactly mimics the same issue I am having in my project. Thanks for the help, and please let me know if you need any more information!

**Comment by menehune23** [comment]
Also, `raml-mockup -v` => raml-mockup 0.1.6

**Comment by ghost** [comment]
Resolved by building manually and stating specific known working `json-schema-faker` version:

```
diff --git a/package.json b/package.json
index f91d130..10b1162 100644
--- a/package.json
+++ b/package.json
@@ -21,7 +21,7 @@
     "cli-color-tty": "^1.0.1",
     "express": "^4.12.3",
     "gaze": "^0.5.1",
-    "json-schema-faker": "^0.2.2",
+    "json-schema-faker": "0.2.2",
     "lodash": "^2.4.2",
     "minimist": "^1.1.1",
     "raml-parser": "^0.8.14",
```

**Comment by ghost** [comment]
@pateketrueke Seems like you updated the dependencies again in the latest commit causing this issue to reappear.

I have narrowed the issue to be a side effect of updating `json-schema-faker` to `0.2.3` or above. I have not looked into what changed in `json-schema-faker` to cause this issue to occur but keeping a static version dependency might be the most certain way to maintain stability.

**Comment by pateketrueke** [comment]
Did you test with v0.2.5 ?

**Comment by ghost** [comment]
Just did:

```
[master][/tmp/raml-mockup]$ npm ls | grep faker
├─┬ json-schema-faker@0.2.5
│ ├── faker@3.0.1
└─┬ refaker@0.3.0

[master][/tmp/raml-mockup]$ ./bin/cli.js spec/fixtures/api.raml -d spec/fixtures/schemas -f http://json-schema.org -p 5000 -r /tmp/raml-mockup/spec/formats/index.js -w

[master][/tmp/raml-mockup]$ curl http://localhost:5000/songs
{"error":"Reference not found: http://json-schema.org/song-schema.json#"}
```

**Comment by pateketrueke** [comment]
From which folder are you executing raml-mockup?

**Comment by ghost** [comment]
In this case base directory. Is there a specific directory you would like me to try? I have also tried absolute paths.

**Comment by pateketrueke** [comment]
I've ran the same command from the spec folder without issues...

Do you have a repository or gist with your schemas?

**Comment by ghost** [comment]
We are testing this issue on the schemas in this repo. No changes. You should be able to pull down the repo and run...

Note: If you have the original 0.1.6 version installed it was probably using the old `json-schema-faker` version. New installations will use new `json-schema-faker` version.

```
cd raml-mockup

# Clean up old versions
sudo npm uninstall -g .

# Install new version
sudo npm install -g .

# Run server
raml-mockup $PWD/spec/fixtures/api.raml -d $PWD/spec/fixtures/schemas -f http://json-schema.org -p 5000 -r $PWD/spec/formats/index.js -w

# Call endpoint (New window)
http http://localhost:5000/songs

# Result
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Headers: Content-Type, Content-Length
Access-Control-Allow-Methods: *
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Accept-Ranges, Content-Encoding, Content-Length, Content-Range
Connection: keep-alive
Content-Length: 73
Content-Type: application/json; charset=utf-8
Date: Tue, 08 Dec 2015 01:36:43 GMT
ETag: W/"49-bvn4r+XrLSrRCKXb4c3LzA"
X-Powered-By: Express

{
    "error": "Reference not found: http://json-schema.org/song-schema.json#"
}
```

**Comment by pateketrueke** [comment]
You're right, I found the issue: refaker/deref was causing the bug.

I've released patches from both libraries and updated the dependencies, could you pull and test again?

**Comment by ghost** [comment]
Sweet! Works like a charm.
