### ISSUE TITLE
Question about example with RAML document

### ISSUE THREAD

**Issue by briviere** [tacoss/raml-mockup#8]
This is more of a question then and issue but does raml-mockup us the examples provided within RAML document?  I do have examples included but it does not appear to be using them.

thanks

Brian

**Comment by pateketrueke** [comment]
Yeah, actually you can use the option [`_forceExample`](https://github.com/gextech/raml-mockup#queryparams) to enforce raml-mockup to use the found example rather than generating a mock...

**Comment by briviere** [comment]
I see,  query parameters.

thanks

Brian

**Comment by pateketrueke** [comment]
It that worked for you?

**Comment by briviere** [comment]
yes
